version: '3'

services:

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    # network_mode: "host"
    # privileged: true
    ports:
      - 50000:50000

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    # network_mode: "host"
    ports:
      - 5000:5000
    depends_on:
      - server

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    depends_on:
      - backend

  nginx:
    image: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 8080:8080
    depends_on:
      - backend
      - frontend
